/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation("io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.1.0")
    implementation("org.springframework.boot:spring-boot-gradle-plugin:2.7.8")
    implementation("com.google.cloud.tools.jib:com.google.cloud.tools.jib.gradle.plugin:3.1.4")
}

val JAVA_LANGUAGE_VERSION = 11

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(JAVA_LANGUAGE_VERSION))
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = "$JAVA_LANGUAGE_VERSION"
    }
}