/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idl.poc.app;

import idl.poc.list.LinkedList;

import static idl.poc.utilities.StringUtils.join;
import static idl.poc.utilities.StringUtils.split;
import static idl.poc.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
